### PR TITLE
CD-971

### PR DESCRIPTION
**Pull request by c3foto**
Update helm app version for CKS and CSE

### CODE REVIEW

**Comment by strantalis** [comment]
@c3foto Are the deletion of the older chart packages going to break anything? Not sure if they are getting consumed?

**Comment by c3foto** [comment]
@strantalis They shouldn't affect anything, I left the latest version of each just in case but several versions back shouldn't affect anything that I know of.

**Comment by c3foto** [comment]
@strantalis I can add them back if you think it will cause an issue, I was just trying to clean up the clutter.

**Comment by strantalis** [comment]
> @strantalis I can add them back if you think it will cause an issue, I was just trying to clean up the clutter.
I am okay removing them I just wasn't sure if they anyone was using older versions.

**Review by strantalis — APPROVED** [review]

**Pull request merged**
